GET http://localhost:8080/horses/644
###
DELETE http://localhost:8080/horses/delete/931
###
GET http://localhost:8080/horses/all
###
POST http://localhost:8080/sports/add
Content-Type: application/json

{
"name":  "Polo"
}

###
POST http://localhost:8080/horses/add
Content-Type: application/json


{
    "name": "Pferd1",
    "dob":  "2000-01-01",
    "sex": "Female",
    "favoriteSport": {"name":  "Polo"}


}

###
PUT http://localhost:8080/horses/update
Content-Type: application/json


{
    "id": 835,
    "name": "TlukaaaaaaasFickt",
    "dob":  "2080-01-01",
    "sex": "Female",
    "favoriteSport": {"name":  "Polo"},
    "dad": {"name":  "Vater", "dob":  "1999-01-01", "sex":  "Male"}

}
